### ISSUE TITLE
Wrong error text for unsuccessful Unlock()

### ISSUE THREAD

**Issue by pavelpatrin** [go-redsync/redsync#107]
Unsuccessful Unlock() returns error related to Lock().

```
lock already taken, locked nodes: [0]
```

But I tried to unlock, not lock.

**Comment by hjr265** [comment]
@pavelpatrin Could you please share some snippet of code that reliably reproduces this?

**Comment by mingLvft** [comment]
开始获取锁
开始获取锁
获取锁成功
panic: lock already taken, locked nodes: [0]

goroutine 19 [running]:
main.main.func1()
        /Users/ming/www/Go/src/mingshop_srvs/inventory_srv/utils/redis_lock/main.go:39 +0x1f8
created by main.main
        /Users/ming/www/Go/src/mingshop_srvs/inventory_srv/utils/redis_lock/main.go:33 +0x148

Process finished with the exit code 2

**Comment by mingLvft** [comment]
Time.Sleep is set to report an error in 5 seconds (4 seconds is normal), but NewMutex configuration defaults to 8 seconds,

**Comment by hjr265** [comment]
@mingLvft The `Lock` and `LockContext` functions will return after trying a set number of times to acquire the lock. If it sees that the lock is already taken and the number of retries have been exhausted, it will simply return the error `ErrTaken`.

This is how the Redlock algorithm is meant to work. See https://redis.io/docs/manual/patterns/distributed-locks/#retry-on-failure.

What you can do is increase the number of retries with `WithTries` (additionally increase the retry delay with `WithRetryDelay` or `WithRetryDelayFunc` to give the mutex more time to acquire the lock).

**Comment by molon** [comment]
> Time.Sleep is set to report an error in 5 seconds (4 seconds is normal), but NewMutex configuration defaults to 8 seconds,

`expiry` means the life of the mutex, does not means wait-lock time.
But I think the default `delay*tries` should exceed the default `expiry`, otherwise it is easy to cause confusion.

**Comment by mingLvft** [comment]
Thank you so much for your help, my friend from another country.

**Comment by OrkhanAlikhanov** [comment]
@hjr265 I run into this issue too. If lock is already released, trying to release it again errors `lock already taken, locked nodes: [0]`.

```go
mutex := rs.NewMutex("my-global-mutex")

if err := mutex.Lock(); err != nil {
	panic(err)
}

if ok, err := mutex.Unlock(); !ok || err != nil {
	panic(err)
}

println("Releasing again")
if ok, err := mutex.Unlock(); !ok || err != nil {
	panic(err) /// lock already taken, locked nodes: [0]
}
```

This happens when TTL is lower than the duration of the work done. In the example TTL is set to 2 seconds and work takes 5 seconds. After the work is done, trying to release lock fails with `lock already taken`

```go
package main

import (
	"github.com/go-redsync/redsync/v4"
	"github.com/go-redsync/redsync/v4/redis/goredis/v9"
	goredislib "github.com/redis/go-redis/v9"
	"log"
	"time"
)

func main() {
	// Create a pool with go-redis (or redigo) which is the pool redisync will
	// use while communicating with Redis. This can also be any pool that
	// implements the `redis.Pool` interface.
	client := goredislib.NewClient(&goredislib.Options{
		Addr: "localhost:6379",
	})
	pool := goredis.NewPool(client) // or, pool := redigo.NewPool(...)

	// Create an instance of redisync to be used to obtain a mutual exclusion
	// lock.
	rs := redsync.New(pool)

	// Obtain a new mutex by using the same name for all instances wanting the
	// same lock.
	mutexname := "my-global-mutex"
	mutex := rs.NewMutex(mutexname, redsync.WithExpiry(2*time.Second))

	// Obtain a lock for our given mutex. After this is successful, no one else
	// can obtain the same lock (the same mutex name) until we unlock it.
	if err := mutex.Lock(); err != nil {
		log.Print(err)
		return
	}

	log.Print("Lock acquired. Doing some 5 second work...")
	time.Sleep(5 * time.Second)
	log.Print("Work done. Releasing lock")

	// Release the lock so other processes or threads can obtain a lock.
	if ok, err := mutex.Unlock(); !ok || err != nil {
		log.Print(err)
	} else {
		log.Print("Lock released")
	}
}
```
